# Generated by Django 4.1.1 on 2022-10-06 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='contact_no')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='driver_details',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('driver_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('bus_no', models.CharField(max_length=6)),
                ('bus_type', models.CharField(choices=[('Super Luxury-Ac', 'Super Luxury-Ac '), ('Ultra Deluxe-NonAc', 'Ultra Deluxe-NonAc'), ('Super Luxury-NonAc', 'Super Luxury-NonAc'), ('Luxury-Ac', 'Luxury-Ac '), (' Luxury-NonAc', 'Luxury-NonAc'), ('Garuda-Ac', 'Garuda-Ac'), ('Ultra Deluxe -Ac', 'Ultra Deluxe-Ac ')], max_length=20)),
                ('seat_type', models.CharField(choices=[('sleeper', 'sleeper'), ('semi-sleeper', 'semi-sleeper'), ('Normal', 'Normal')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('fare', models.IntegerField()),
                ('driver_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver_details')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.DateField()),
                ('Booking_end_date', models.DateField()),
                ('no_of_passengers', models.IntegerField()),
                ('booking_Bus_details', models.OneToOneField(default='Anonymus', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.buses')),
                ('booking_cust_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
