# Generated by Django 4.1.1 on 2022-10-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='not_booked_seats',
            field=models.IntegerField(default=25),
        ),
    ]
