# Generated by Django 4.1.1 on 2022-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='Balance',
            field=models.IntegerField(default=0),
        ),
    ]
