# Generated by Django 4.1.1 on 2022-10-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='wallet',
        ),
    ]
