# Generated by Django 4.1.1 on 2022-10-10 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_balance_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='destination',
            field=models.CharField(choices=[('Bhadrachalam', 'Bhadrachalam'), ('chittor', 'Chittor'), ('ahmedabad', 'ahmedabad'), ('vizag', 'vizag'), ('pune', 'Pune'), ('chittor', 'Chittor'), ('Banglore', 'Banglore'), ('rajastan', 'rajastan'), ('chennai', 'chennai'), ('Hyderabad', 'Hyderabad'), ('Nellore', 'Nellore')], max_length=30),
        ),
        migrations.AlterField(
            model_name='buses',
            name='origin',
            field=models.CharField(choices=[('Ongole', 'Ongole'), ('delhi', 'delhi'), ('rjy', 'Rajuhmundry'), ('kakinada', 'kakinada'), ('kolkata', 'Kolkata'), ('delhi', 'Delhi'), ('Chennai', 'Chennai'), ('mumbai', 'Mumbai'), ('Hyderabad', 'Hyderabad'), ('Banglore', 'Banglore'), ('kadapa', 'kadapa')], max_length=30),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
