# Generated by Django 4.1.1 on 2022-10-11 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='driver_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='accounts.driver_details'),
        ),
    ]
