# Generated by Django 4.1.1 on 2022-10-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_buses_driver_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='destination',
            field=models.CharField(choices=[('Ongole', 'Ongole'), ('Bhadrachalam', 'Bhadrachalam'), ('chittor', 'Chittor'), ('ahmedabad', 'Ahmedabad'), ('vizag', 'vizag'), ('pune', 'Pune'), ('chittor', 'Chittor'), ('Banglore', 'Banglore'), ('rajastan', 'rajastan'), ('chennai', 'chennai'), ('Hyderabad', 'Hyderabad'), ('Nellore', 'Nellore'), ('bhopal', 'Bhopal'), ('vijayawada', 'vijayawada'), ('srinagar', 'Srinagar'), ('kanpur', 'Kanpur'), ('patna', 'Patna'), ('indore', 'Indore')], max_length=30),
        ),
        migrations.AlterField(
            model_name='buses',
            name='origin',
            field=models.CharField(choices=[('Banglore', 'Banglore'), ('Chennai', 'Chennai'), ('Hyderabad', 'Hyderabad'), ('Noida', 'Noida'), ('Ongole', 'Ongole'), ('delhi', 'delhi'), ('indore', 'Indore'), ('jammu', 'Jammu'), ('kadapa', 'kadapa'), ('kakinada', 'kakinada'), ('kanpur', 'Kanpur'), ('kochi', 'Kochi'), ('kolkata', 'Kolkata'), ('lucknow', 'Lucknow'), ('mumbai', 'Mumbai'), ('nagpur', 'Nagpur'), ('nellore', 'Nellore'), ('patna', 'Patna'), ('rjy', 'Rajuhmundry')], max_length=30),
        ),
    ]
