# Generated by Django 4.1.1 on 2022-10-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_bookings_booking_bus_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='Booking_date',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='Booking_end_date',
        ),
    ]
