# Generated by Django 4.1.1 on 2022-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=6)),
                ('bus_type', models.CharField(choices=[('Super Luxury-Ac', 'Super Luxury-Ac '), ('Ultra Deluxe-NonAc', 'Ultra Deluxe-NonAc'), ('Super Luxury-NonAc', 'Super Luxury-NonAc'), ('Luxury-Ac', 'Luxury-Ac '), (' Luxury-NonAc', 'Luxury-NonAc'), ('Garuda-Ac', 'Garuda-Ac'), ('Ultra Deluxe -Ac', 'Ultra Deluxe-Ac ')], max_length=20)),
                ('seat_type', models.CharField(choices=[('sleeper', 'sleeper'), ('semi-sleeper', 'semi-sleeper'), ('Normal', 'Normal')], max_length=20)),
                ('not_booked_seats', models.IntegerField(default=25)),
            ],
        ),
    ]
