# Generated by Django 4.1.1 on 2022-10-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_buses_bus_no_remove_buses_bus_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='buses',
            name='driver_details',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Buses',
        ),
        migrations.DeleteModel(
            name='driver_details',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
