# Generated by Django 4.1.1 on 2022-11-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date created'),
        ),
    ]
