# Generated by Django 4.1.1 on 2022-09-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('dod', models.DateField()),
            ],
        ),
    ]
